language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
    - composer install
    - echo 'date.timezone = "America/Los_Angeles"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: phpunit
