language: php

php:
  - '5.6'
  - '7.0'

install:
    - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script:
    - composer install
    - wget https://s3-us-west-2.amazonaws.com/csvelte/csvsampledata.tar.gz
    - tar xvfz csvsampledata.tar.gz -C tests/
    - echo 'date.timezone = "America/Los_Angeles"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: phpunit -c phpunit.xml

notifications:
  email:
    - luke.visinoni@gmail.com
    - luke@visinoni.net
